language: java
jdk:
- oraclejdk7
- openjdk6
deploy:
  provider: releases
  api_key:
    secure: "S/XfQ99w1fW/kLs+AUEJ1n4dG0dF8nhX+O25oGKM4xdyqJYeIQskvpUeAoFPaoYkmWF4m5rnZwhpq8PTBTLkSIx+fUrrwBw/UJQ6sN07ooyRHn0U1KbUGx3EpW+E1gN4Wq4dK/9fuEFDXuXzCqTLhHaoOpSsQ6A3UGdRV3bYYvqJaiGsNNgKUr+SASqJmJDCyf5DIQs5Hsmgdk2Q1FN22m2bwAP9Qc2OkKDv9Y0fSwCb1j7stEJydQhjF7y2QfTjiIEZJQQNEOLUuLajCmkb9ONm/9nulv/BdfEWkJJnZTjErpNqzvmdaGJAYdxJJ/JL0AYMcR0g9IlmgnIy9YxlOa6KwPuw+iwHtyvnQstkj98R+y399pQg5Lr9pAOFpE8M7cM47p1K3j+muA26axGzez0sHPQhCGjaxM5il15mnkGWmIYXaMsI2e8nFwLTzDNs/C+xTiw2t4mcghTvXf8jfi0MqW2om+B1dZlMthtHDTyd5J9CD1F2SSVJKp/iarYJObJjlOIie1PAE4gzmr8qFTn7N15Uo4AqotPK2M4m07UpI0GWsEmjy0gBTAy/+VtOuyx5sJa2CM4ygTkGqO1iBP/pfgBoOoKqx59VfCKj9xbMayomDewGVKad1KXyRtqNz2NDdsVLG3zO22Q2rDOviy1ch5IZhnj9zbyvED0cSbw="
  file: target/dynaslave.hpi
  on:
    repo: solaress1980/dynaslave-plugin
    tags: true
